some reworks for standards
discoverygarden/islandora_solution_pack_ead pull request #1
Opened 2019-02-01 19:49 UTC by qadan

2019-02-05 13:25 UTC, jordandukart requested changes

2019-02-05 13:25 UTC, jordandukart commented on includes/ead_upload.form.inc
> +    $unitid = $eadxp->query('/ead:ead/ead:archdesc/ead:did/ead:unitid');
Couldn't these be `$eadxp->evaluate('string(whateverxpath)')` or normalize-space/whatever?

2019-02-05 13:25 UTC, jordandukart commented on includes/manage.form.inc
> +  if (!isset($object['EAD'])) {
Instead of this would it make sense to modify the manage callback to not provide a link to the form if there is no EAD?

2019-02-05 13:25 UTC, jordandukart commented on js/eadPopovers.js
> +        $(this).popover({ trigger: 'hover', content: img, html: true });
`popover` seems to be a Bootstrap function which we aren't including/marking a dependency of thus this function still does not work.

2019-02-05 13:25 UTC, jordandukart commented on includes/ead_upload.form.inc
> +  $eadxp->registerNamespace('ead', 'http://ead3.archivists.org/schema/');
Pretty sure this isn't the correct namespace as the title query below fails in regression testing.

2019-02-05 20:46 UTC, qadan commented on js/eadPopovers.js
> +        $(this).popover({ trigger: 'hover', content: img, html: true });
The overhead of adding Bootstrap as a dependency and loading it on these view pages just so we can get thumbnails on hover does not seem worth it. Culling this popover piece.

2019-02-06 16:55 UTC, jordandukart commented on includes/ead_upload.form.inc
> +      '@id' => $unitid ? "$unitid " : "",
You goofed your replacements.

2019-02-06 19:34 UTC, merged